import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"/>
        <title>Add posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-center">
        <h1 className='p-5'>Hello and welcome to my Mongo Next experiment!</h1>
        <h3 className='p-5'>Navigate to either add a new post or see all existing ones:</h3>
        <hr />
        <div className='flex justify-evenly mt-10'>
          <Link className='p-2 shadow' href="/all-posts">All Posts</Link>
          <Link className='p-2 shadow' href="/new-post">Аdd a new post</Link>
        </div>
      </main>
    </>
  )
}
